# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hemonucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='outrosDados',
            field=models.CharField(default='ola', max_length=200, verbose_name=b'Outros'),
            preserve_default=False,
        ),
    ]
